### ISSUE TITLE
Gradle徹底入門読書会 2015

### ISSUE THREAD

**Issue by grimrose** [yokohamagroovy/support#11]
## 内容

http://www.shoeisha.co.jp/book/detail/9784798136431

Gradle徹底入門を参考書に、読書会を開催する
## 目標

Gradleのプラグインが書けるくらいのスキルを得る
## スケジュール
- 導入編で気になったことや躓いたことは、初回に共有する
- 基礎編
  - 2回くらいを予定
- 発展編
  - プラグインの使い方を知る
  - プラグインの読み方を知る
  - プラグインの書き方を知る
  - etc...
- ハンズオン
  - WebアプリをGradleプロジェクト作ってみる
  - 上記で作ったWebアプリにpluginを加えてみる
  - デプロイまでやってみる

**Comment by yukung** [comment]
:+1:

**Comment by grimrose** [comment]
基礎編(4-7章)は1回で終了出来た。

**Comment by grimrose** [comment]
実践編ではSpring bootのアプリケーションを作ってみて、第8章の内容を実施してみたいと思います。
